-- MySQL Script generated by MySQL Workbench
-- Thu Jul  1 12:18:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricule` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `prenoms` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `fonction` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entreprise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricule` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `responsable` VARCHAR(45) NULL,
  `contactRespo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mat` VARCHAR(50) NULL,
  `libelleProjet` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  `entreprise_id` INT NOT NULL,
  PRIMARY KEY (`id`, `entreprise_id`),
  INDEX `fk_projet_entreprise1_idx` (`entreprise_id` ASC) VISIBLE,
  CONSTRAINT `fk_projet_entreprise1`
    FOREIGN KEY (`entreprise_id`)
    REFERENCES `mydb`.`entreprise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`niveauEvolution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`niveauEvolution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`taches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`taches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomTache` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `delaisExec` VARCHAR(45) NULL,
  `etatEvolution` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `projet_id` INT NOT NULL,
  `projet_entreprise_id` INT NOT NULL,
  `niveauEvolution_id` INT NOT NULL,
  PRIMARY KEY (`id`, `projet_id`, `projet_entreprise_id`, `niveauEvolution_id`),
  INDEX `fk_taches_projet1_idx` (`projet_id` ASC, `projet_entreprise_id` ASC) VISIBLE,
  INDEX `fk_taches_niveauEvolution1_idx` (`niveauEvolution_id` ASC) VISIBLE,
  CONSTRAINT `fk_taches_projet1`
    FOREIGN KEY (`projet_id` , `projet_entreprise_id`)
    REFERENCES `mydb`.`projet` (`id` , `entreprise_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taches_niveauEvolution1`
    FOREIGN KEY (`niveauEvolution_id`)
    REFERENCES `mydb`.`niveauEvolution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ressourcesTache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ressourcesTache` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `lien` VARCHAR(45) NULL,
  `taches_id` INT NOT NULL,
  `taches_projet_id` INT NOT NULL,
  `taches_projet_entreprise_id` INT NOT NULL,
  `taches_niveauEvolution_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `taches_id`, `taches_projet_id`, `taches_projet_entreprise_id`, `taches_niveauEvolution_id`),
  INDEX `fk_ressourcesTache_taches1_idx` (`taches_id` ASC, `taches_projet_id` ASC, `taches_projet_entreprise_id` ASC, `taches_niveauEvolution_id` ASC) VISIBLE,
  CONSTRAINT `fk_ressourcesTache_taches1`
    FOREIGN KEY (`taches_id` , `taches_projet_id` , `taches_projet_entreprise_id` , `taches_niveauEvolution_id`)
    REFERENCES `mydb`.`taches` (`id` , `projet_id` , `projet_entreprise_id` , `niveauEvolution_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `info` VARCHAR(45) NULL,
  `message` VARCHAR(45) NULL,
  `statut` VARCHAR(45) NULL,
  `destinataire` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_notifications_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commentairesTache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commentairesTache` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  `taches_id` INT NOT NULL,
  `taches_projet_id` INT NOT NULL,
  `taches_projet_entreprise_id` INT NOT NULL,
  `taches_niveauEvolution_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `taches_id`, `taches_projet_id`, `taches_projet_entreprise_id`, `taches_niveauEvolution_id`, `user_id`),
  INDEX `fk_commentairesTache_taches1_idx` (`taches_id` ASC, `taches_projet_id` ASC, `taches_projet_entreprise_id` ASC, `taches_niveauEvolution_id` ASC) VISIBLE,
  INDEX `fk_commentairesTache_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentairesTache_taches1`
    FOREIGN KEY (`taches_id` , `taches_projet_id` , `taches_projet_entreprise_id` , `taches_niveauEvolution_id`)
    REFERENCES `mydb`.`taches` (`id` , `projet_id` , `projet_entreprise_id` , `niveauEvolution_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentairesTache_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_has_role_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respoProjet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respoProjet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `projet_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `projet_id`),
  INDEX `fk_user_has_projet_projet1_idx` (`projet_id` ASC) VISIBLE,
  INDEX `fk_user_has_projet_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_projet_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_projet_projet1`
    FOREIGN KEY (`projet_id`)
    REFERENCES `mydb`.`projet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_taches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_taches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `taches_id` INT NOT NULL,
  `taches_projet_id` INT NOT NULL,
  `taches_projet_entreprise_id` INT NOT NULL,
  `taches_niveauEvolution_id` INT NOT NULL,
  `user_has_tachescol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `user_id`, `taches_id`, `taches_projet_id`, `taches_projet_entreprise_id`, `taches_niveauEvolution_id`),
  INDEX `fk_user_has_taches_taches1_idx` (`taches_id` ASC, `taches_projet_id` ASC, `taches_projet_entreprise_id` ASC, `taches_niveauEvolution_id` ASC) VISIBLE,
  INDEX `fk_user_has_taches_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_taches_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_taches_taches1`
    FOREIGN KEY (`taches_id` , `taches_projet_id` , `taches_projet_entreprise_id` , `taches_niveauEvolution_id`)
    REFERENCES `mydb`.`taches` (`id` , `projet_id` , `projet_entreprise_id` , `niveauEvolution_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
